# ===== Server =====

server.port=8081

# ===== Database =====
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
# 'update' = auto-create or update tables on startup. Perfect for dev, NEVER for production.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== JWT =====
# This is the secret key used to sign JWT tokens
# Must be at least 256 bits (32 chars) for HS256.
app.jwt.secret=ThisIsAVeryLongSecretKeyForChatAppDoNotUseInProduction12345
app.jwt.expiration-ms=86400000

# ===== Logging =====
logging.level.org.springframework.security=DEBUG
logging.level.com.chatapp=DEBUG
